# Generated by Django 4.2.4 on 2023-08-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
