# Generated by Django 4.2.4 on 2023-08-10 15:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0004_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serivieinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
