# Generated by Django 4.2.4 on 2023-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0005_serivieinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serivieinfo',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
