# Generated by Django 4.2.4 on 2023-08-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0008_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
