# Generated by Django 4.2.4 on 2023-08-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0010_abt_us_abt_us1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abt_us',
            name='about',
            field=models.CharField(max_length=800),
        ),
    ]
