# Generated by Django 4.2.4 on 2023-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0011_alter_abt_us_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
