# Generated by Django 4.2.4 on 2023-08-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0012_alter_carouselitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexser',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
