# Generated by Django 4.2.4 on 2023-08-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0013_alter_indexser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('postion', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
